name: test

on:
  push:
  pull_request:

jobs:
  forge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        working-directory: contracts
        run: |
          forge install foundry-rs/forge-std
          forge install OpenZeppelin/openzeppelin-contracts@v5.1.0

      - name: Build
        working-directory: contracts
        run: forge build

      - name: Test
        working-directory: contracts
        run: forge test -vv
